# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  domain: "hzbxhd.com"

# MySQL数据库配置
mysql:
  host: "192.168.6.3"
  port: 3306
  username: "root"
  password: "root"
  database: "cmdb"

# Redis配置
redis:
  host: "192.168.6.3"
  port: 6379
  password: "redis"
  db: 1

# Prometheus配置
prometheus:
  host: "192.168.3.10"
  port: 63010

# Kubernetes配置
kubernetes:
  config_path: "admin.conf"

# 安全配置
security:
  jwt_secret: "PjdDQW8b8lTCUwuYP49KbtIeyLbon1bn"
  password_salt: "7WJb2xLz3XMb1f7upQV4RX1yIkEsgF2a"